name: Tests
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set environment variables from .env
        uses: xom9ikk/dotenv@v2.2.0
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run tests
        run: go test -v ./...
        env:
          VAULT_ACC: '1'
          TEST_BACKBLAZEB2_APPLICATION_KEY_ID: ${{ secrets.TEST_BACKBLAZEB2_APPLICATION_KEY_ID }}
          TEST_BACKBLAZEB2_APPLICATION_KEY: ${{ secrets.TEST_BACKBLAZEB2_APPLICATION_KEY }}